GET http://localhost:9999/api/wallet/exist/b
###+
POST http://localhost:9999/api/wallet/register
Content-Type: application/json

{
  "username": "9",
  "phone": "9",
  "password": "12345678"
}
###+
POST http://localhost:9999/api/wallet/transaction
X-UserID: 2
Content-Type: application/json

{
  "acc_id": 2,
  "amount": 300
}
###+
GET http://localhost:9999/api/wallet/transactions
X-UserID: 2
###+
GET http://localhost:9999/api/wallet/account
X-UserID: 2
###+
GET http://localhost:9999/api/wallet/balance
X-UserID: 2
###+
POST http://localhost:9999/api/wallet/identify
X-UserID: 2
###+
